# Generated by Django 5.0.6 on 2024-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boglanish',
            name='xarita',
        ),
        migrations.AddField(
            model_name='boglanish',
            name='latitude',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boglanish',
            name='longitud',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
